import fs from 'fs'

export async function generateContent(type){

    const data = {
        title: 'AI Generated Page',
        description: 'Generated by AI system',
        created: new Date().toISOString()
    }

    const path = './content/' + type + '.json'

    fs.writeFileSync(path, JSON.stringify(data,null,2))

    return {status:'content created', file:path}
}
