name = "theunitedstates-site"
pages_build_output_dir = "dist"
compatibility_date = "2026-04-17"

[vars]
ORG_NAME = "3000Studios"
NETWORK_PRIMARY_DOMAIN = "3000studios.vip"
APP_SLUG = "usa"
APP_DISPLAY_NAME = "The United States"
APP_BASE_URL = "https://usa.3000studios.vip"
ADSENSE_PUBLISHER_ID = "ca-pub-5800977493749262"
